### ISSUE TITLE
Модуль движения. Информация о пройденном расстоянии

### ISSUE THREAD

**Issue by bymse** [Crawiot/Crawiot#10]
Нужно реализовать логику по отслеживанию изменения положения.
При изменении положения нужно менять координаты в `GlobalLocationManager`  
делать это нужно через прерывания

В рамках этой же задачи нужно продумать подключение датчика/датчиков к плате.
Синхронизироваться с #4, чтобы были разные пины

**Comment by bymse** [comment]
https://lastminuteengineers.com/handling-esp32-gpio-interrupts-tutorial/

**Comment by Drlionardo** [comment]
Доступные средства: 
2x Датчик холла https://voltiq.ru/shop/hall-module-ky-003/
Неодимовые магниты
